#$ docker-compose -v
# docker-compose up
# docker-compose up -d
# docker-compose -f Custom_Docker_compose.yml up
# docker-compose -f Custom_Docker_compose.yml up -d

# Version
version: '3.1'

# Services
services:
  backend:
    container_name: task
    image: task
    restart: always
    build: ./
    ports:
      - "4445:4445"
    networks:
      - task_network

# Networks
networks:
  task_network:
    name: task_network
    driver: bridge